# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

language: scala

# TODO - we'd like to actually test everything, but the process library has a deadlock right now
jdk:
  - openjdk6
#  - oraclejdk7

env:
  matrix:
    - SCRIPTED_TEST="safeUnitTests"
    - SCRIPTED_TEST="otherUnitTests"
    - SCRIPTED_TEST="scripted actions/*"
    - SCRIPTED_TEST="scripted api/*"
    - SCRIPTED_TEST="scripted compiler-project/*"
    - SCRIPTED_TEST="scripted dependency-management/*1of2"
    - SCRIPTED_TEST="scripted dependency-management/*2of2"
    - SCRIPTED_TEST="scripted ivy-deps-management/*"
    - SCRIPTED_TEST="scripted java/*"
    - SCRIPTED_TEST="scripted package/*"
    - SCRIPTED_TEST="scripted project/*1of2"
    - SCRIPTED_TEST="scripted project/*2of2"
    - SCRIPTED_TEST="scripted reporter/*"
    - SCRIPTED_TEST="scripted run/*"
    - SCRIPTED_TEST="scripted source-dependencies/*1of3"
    - SCRIPTED_TEST="scripted source-dependencies/*2of3"
    - SCRIPTED_TEST="scripted source-dependencies/*3of3"
    - SCRIPTED_TEST="scripted tests/*"
    - SCRIPTED_TEST="scripted project-load/*"
    - SCRIPTED_TEST="checkBuildScala211"
    - SCRIPTED_TEST="mavenResolverPluginTest:scripted dependency-management/*1of2 project/transitive-plugins"
    - SCRIPTED_TEST="mavenResolverPluginTest:scripted dependency-management/*2of2"

notifications:
  email:
    - eugene.yokota@typesafe.com
    - joshua.suereth@typesafe.com

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m "$SCRIPTED_TEST"

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
